name: Deploy to NCP Server

on:
  push:
    branches: [ main, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to NCP Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.NCP_HOST }}
        username: root
        password: ${{ secrets.NCP_PASSWORD }}
        port: 22
        script: |
          # 기존 앱 백업
          timestamp=$(date +%Y%m%d_%H%M%S)
          cp -r /home/user/app /home/user/app_backup_$timestamp

          # 깃 리포지토리 업데이트
          cd /home/user/app
          git fetch origin
          git reset --hard origin/dev

          # .env 파일 생성
          cat > .env << EOL
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          ENV=production
          URL=${{ secrets.URL }}
          DBPASSWORD=${{ secrets.DBPASSWORD }}
          DBURL=${{ secrets.DBURL }}
          CLIENTSECRET=${{ secrets.CLIENTSECRET }}
          FILEPATH=/home/user/app/uploads
          CLOVAURL=${{ secrets.CLOVAURL }}
          GPTSKEY1=${{ secrets.GPTSKEY1 }}
          GPTSKEY2=${{ secrets.GPTSKEY2 }}
          GPTSKEY3=${{ secrets.GPTSKEY3 }}
          GPTSKEY4=${{ secrets.GPTSKEY4 }}
          GPTSKEY5=${{ secrets.GPTSKEY5 }}
          EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          TOSS_SECRET_KEY=${{ secrets.TOSS_SECRET_KEY }}
          EOL

          # PM2 재시작
          pm2 delete all || true
          pm2 start ecosystem.config.cjs
          pm2 save