name: Deploy to NCP Server

on:
  push:
    branches: [ main, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Deploy to NCP Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.NCP_HOST }}
        username: ${{ secrets.NCP_USERNAME }}
        password: ${{ secrets.NCP_PASSWORD }}
        port: 2222
        script: |
          cd /home/user/app
          git remote remove origin
          git remote add origin https://github.com/WintoPartners/ilovesales_back_svr.git
          git remote -v
          git fetch origin
          git checkout dev || git checkout -b dev origin/dev
          git pull origin dev
          
          # 필수 모듈 설치
          npm install bcrypt
          npm install --omit=dev
          
          # PM2 설정 및 실행
          cp ecosystem.config.cjs /home/user/app/ || echo "Config file already exists"
          pm2 delete all || true  # 기존 프로세스 중지
          pm2 start ecosystem.config.cjs
          pm2 save