name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # .env 파일 생성
    - name: Create .env file
      run: |
        cat > .env << EOL
        OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        ENV=production
        URL=${{ secrets.URL }}
        DBPASSWORD=${{ secrets.DBPASSWORD }}
        DBURL=${{ secrets.DBURL }}
        FILEPATH=/var/app/current/uploads
        CLIENTSECRET=${{ secrets.CLIENTSECRET }}
        CLOVAURL=${{ secrets.CLOVAURL }}
        GPTSKEY1=${{ secrets.GPTSKEY1 }}
        GPTSKEY2=${{ secrets.GPTSKEY2 }}
        GPTSKEY3=${{ secrets.GPTSKEY3 }}
        GPTSKEY4=${{ secrets.GPTSKEY4 }}
        GPTSKEY5=${{ secrets.GPTSKEY5 }}
        EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
        TOSS_SECRET_KEY=${{ secrets.TOSS_SECRET_KEY }}
        NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}
        NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}
        KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
        KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
        EOL

    - name: Create ZIP deployment package
      run: zip -r deploy.zip . -x "*.git*" "*__pycache__*"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.EB_APPLICATION_NAME }}
        environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy.zip
        version_label: ${{ github.sha }}
        wait_for_deployment: true
        wait_for_environment_recovery: 180